# -*- coding: utf-8 -*-
"""LINE AutomateNews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wJoyTduFA2w0OTfxQ6zzwVtwM1Jcy8I2
"""

import os
import requests
from google import genai
from langchain_community.tools import DuckDuckGoSearchRun

# ==========================================
# 1. KREDENSIAL & INISIALISASI
# ==========================================
GOOGLE_API_KEY = "AQ.Ab8RN6IGIrqjYLIgyLRO5yoEXomIocBqGJgsV8UFlTiH1597XA"
LINE_TOKEN = "QUEvwQwOL0qEc+eZIOcPBAA4J2ar+UKRp/2WspfCUFIyC0q0RV0a6SHbc6kqrIDpxO4HDwhIgV4MhQOfL9rR5YWRC0PEY9LytY3haQaME3pcL4/x2kn6IR5kK2+WqOiYjJKzEXrCl2zGes88ypbI7gdB04t89/1O/w1cDnyilFU="
LINE_USER_ID = "Ue8dcece78ec061a172a2203bfb8b9c01"

# Inisialisasi klien resmi Google GenAI terbaru
client = genai.Client(api_key=GOOGLE_API_KEY)

print("🤖 AI sedang mencari berita di internet...")

# ==========================================
# 2. CARI BERITA DENGAN DUCKDUCKGO
# ==========================================
search = DuckDuckGoSearchRun()
hasil_pencarian = search.run("Perkembangan AI minggu ini")

# ==========================================
# 3. SURUH GEMINI MERANGKUMNYA
# ==========================================
print("🧠 AI sedang merangkum berita...")
prompt = f"""
Berdasarkan informasi berita berikut, buatlah ringkasan dalam 3 poin singkat menggunakan bahasa yang santai dan mudah dibaca:

{hasil_pencarian}
"""

# Menggunakan model standar terbaru yang disarankan oleh sistem Google
response = client.models.generate_content(
    model="gemini-3.6-flash",
    contents=prompt,
)
hasil_rangkuman = response.text

# ==========================================
# 4. KIRIM HASILNYA KE LINE
# ==========================================
def kirim_ke_line(pesan):
    url = "https://api.line.me/v2/bot/message/push"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {LINE_TOKEN}"
    }
    payload = {
        "to": LINE_USER_ID,
        "messages": [{"type": "text", "text": pesan}]
    }

    kirim = requests.post(url, headers=headers, json=payload)
    if kirim.status_code == 200:
        print("\n✅ SUKSES! Pesan terkirim ke LINE Anda.")
    else:
        print(f"\n❌ Gagal mengirim pesan. Error: {kirim.text}")

kirim_ke_line(hasil_rangkuman)