name: Run Automate News Agent

on:
  schedule:
    # Berjalan jam 00:00, 07:00, 12:00, dan 18:00 WIB
    - cron: '0 0,5,11,17 * * *'
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install google-genai ddgs requests
          
      - name: Run the bot script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python AutomateNews.py
