name: Run Automate News Agent

on:
  schedule:
    # Berjalan setiap hari jam 07:00 UTC (14:00 WIB)
    - cron: '0 7 * * *'
  workflow_dispatch: # Memungkinkan Anda menjalankan manual lewat tombol web kapan saja

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install google-genai langchain-community duckduckgo-search ddgs requests

      - name: Run the bot script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python ${{ github.workspace }}/AutomateNews.py
